name: Deploy a Amazon EC2

on:
  push:
    branches: [ main ] # Se activa cuando subes algo a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar vía SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}        # <--- Mira que esto se llame igual en Secrets
          username: ${{ secrets.REMOTE_USER }}    # <--- Y esto también
          key: ${{ secrets.SSH_PRIVATE_KEY }}     # <--- Y esto
          port: 22
          script: |
            cd ~/piensos_urbano
            git pull origin main
            npm install
            pm2 restart piensos-api